'''
This file creates plots from the data generated by running disk_test.py. The plots are used to test that
each algorithm reproduces the physics we would expect from the hard disk model.
'''

import os
import numpy as np
import matplotlib.pyplot as plt
import h5py


def disk_multiplot(configs_to_plot, L_values, titles, figure_title, save_path=None):
    '''
    This function plots multiple disk configurations in a single figure. It takes as inputs:
    configs_to_plot: an array of disk configurations to plot,
    titles: an array of titles for each configuration,
    figure_title: the title of the figure - this is placed at the top of the figure,
    (optional) save_path: where to save the figure.
    '''
    fig, axes = plt.subplots(1, len(configs_to_plot), figsize=(12, 3))
    for j, t in enumerate(titles):
        axes[j].set_aspect('equal')
        axes[j].set_ylim(0,L_values[j])
        axes[j].set_xlim(0,L_values[j])
        axes[j].set_yticklabels([])
        axes[j].set_xticklabels([])
        axes[j].set_yticks([])
        axes[j].set_xticks([])
        axes[j].set_title(t)
        for x,y in configs_to_plot[j]:
            # consider all horizontal and vertical copies that may be visible
            for x_shift in [z for z in x + [-L_values[j],0,L_values[j]] if -1<z<L_values[j]+1]:
                for y_shift in [z for z in y + [-L_values[j],0,L_values[j]] if -1<z<L_values[j]+1]:
                    axes[j].add_patch(plt.Circle((x_shift,y_shift),1))
    plt.suptitle(figure_title, y=0.92)
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.show()
    return


# Load the data
path = os.path.join(os.getcwd(), 'Disk Model', 'Data', 'disk_test.hdf5')
f = h5py.File(path, 'r')

algorithms = ['metropolis_hastings', 'cluster']

# Plot the configurations
for algorithm in algorithms:
    configs = f[f'config_{algorithm}'][:]
    disk_multiplot(configs, [100]*len(configs), 
                   ['Initial', '1 step', '10 steps', '100 steps', '1000 steps', '10000 steps'], 
                   'Evolution of the disk configuration with algorithm iterations', 
                   save_path=os.path.join(os.getcwd(), 'Disk Model', 'Figures', f'{algorithm}_configurations.png'))
