'''
This file creates plots of the runtimes of the generalized Metropolis-Hastings and generalized cluster 
algorithms for the hard disk model as a function of the disk number N based on data generated by running 
dm_complexity.py.
'''
import os
import numpy as np
import matplotlib.pyplot as plt
import h5py

# Parameters
N_values = [20, 40, 60, 80, 100, 120, 140]
steps = 500
algorithms = ['generalized_mh', 'generalized_cluster']

# Load data
path = os.path.join(os.getcwd(), 'Disk Model', 'Data', 'dm_complexity.hdf5')
f = h5py.File(path, 'r')
runtimes_generalized_mh = f['runtimes_generalized_mh'][:]
runtimes_generalized_cluster = f['runtimes_generalized_cluster'][:]
f.close()

# Plot runtimes
plt.plot(N_values, runtimes_generalized_mh/steps, label='Generalized Metropolis-Hastings')
plt.plot(N_values, runtimes_generalized_cluster/steps, label='Generalized Cluster')
plt.plot(N_values, 1e-6*np.array(N_values)**3, label='$\propto N^3$')
plt.xlabel('Disk number N')
plt.ylabel('Runtime per iteration/s')
plt.title('Runtime per iteration vs disk number')
plt.legend()
plt.yscale('log')
plt.xscale('log')
plt.savefig(os.path.join(os.getcwd(), 'Disk Model', 'Figures', 'dm_complexity.png'), dpi=300, bbox_inches='tight')
plt.show()
