'''
This file creates plots from the data generated by running ising_test.py. The plots are used to test that 
each algorithm reproduces the physics we would expect from the 2D Ising model.
'''
import os
import numpy as np
import matplotlib.pyplot as plt
import h5py


def lattice_multiplot(lattices_to_plot, titles, figure_title, save_path=None):
    '''
    This function plots multiple lattices in a single figure. It takes as inputs: 
    lattices_to_plot: an array of lattices to plot,
    titles: an array of titles for each lattice,
    figure_title: the title of the figure - this is placed at the top of the figure,
    (optional) save_path: where to save the figure.
    '''
    fig, axes = plt.subplots(1, len(lattices_to_plot), figsize=(12, 3))
    for j, t in enumerate(titles):
        axes[j].imshow(lattices_to_plot[j], cmap='gray')
        axes[j].set_xticks([])
        axes[j].set_yticks([])
        axes[j].set_title(t)
    plt.suptitle(figure_title, y=0.92)
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.show()
    return

def magnetization_plot(rel_mag_array, a_values, save_path=None):
    '''
    This function plots the relative magnetization of the lattice as a function of a. It takes as inputs:
    rel_mag_array: an array of the relative magnetization at each value of a,
    a_values: an array of values of a,
    (optional) save_path: where to save the figure.
    ''' 
    # Theoretical prediction
    x_0 = np.linspace(0, 0.441, 1000)
    x_1 = np.linspace(0.441, 1, 1000)
    supercritical = np.zeros(1000)
    subcritical_pos = (1 - (np.sinh(2*x_1))**(-4)) ** (1/8)
    x = np.append(x_0, x_1)
    predicted_rel_mag_pos = np.append(supercritical, subcritical_pos)
    
    # Plot
    plt.plot(x, predicted_rel_mag_pos, 'k-', label='Theoretical prediction')
    plt.plot(a_values, rel_mag_array, 'ro', label='Simulated values')
    plt.xlabel('a')
    plt.ylabel('Absolute relative magnetization')
    plt.title(f'Absolute relative magnetization as a function of a')
    plt.legend()
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.show()
    return


# Load the data
path = os.path.join(os.getcwd(), 'Ising', 'Data', 'ising_test.hdf5')
f = h5py.File(path, 'r')

# Parameters
algorithms = ['metropolis_hastings', 'wolff']
a_values = [0.4, 0.6]
titles = ['t = 0', 't = 1', 't = 10', 't = 100', 't = 1000']

# Plot the lattice at each of the sampled times and save the figure
for algorithm in algorithms:
    for i, a in enumerate(a_values):
        lattices = f[f'lattice_{algorithm}_{a}']
        lattices_to_plot = [lattices[j, :, :] for j in range(5)]
        lattice_multiplot(lattices_to_plot, titles, f'Evolution of the lattice with a = {a}', 
                          save_path=os.path.join(os.getcwd(), 'Ising', 'Figures', f'lattice_{algorithm}_{a}.png'))
        
# Plot the relative magnetization vs a for each algorithm
a_values = [0.1, 0.3, 0.4, 0.43, 0.45, 0.5, 0.6, 0.8, 1]
a_values.reverse()

for algorithm in algorithms:
    rel_mag_array = f[f'rel_mag_{algorithm}'][:]
    magnetization_plot(rel_mag_array, a_values, 
                       save_path=os.path.join(os.getcwd(), 'Ising', 'Figures', f'rel_mag_{algorithm}.png'))
