'''
This file creates plots of the runtimes of the Metropolis-Hastings and Wolff algorithms for the 2D Ising model as a function of the system size N.
based on data generated by running ising_complexity.py.
'''
import os
import numpy as np
import matplotlib.pyplot as plt
import h5py

# Parameters
N_values = [64, 128, 256, 512, 1024, 2048]
steps = 500

# Load data
path = os.path.join(os.getcwd(), 'Ising', 'Data', 'ising_complexity.hdf5')
f = h5py.File(path, 'r')
runtimes_metropolis_hastings = f['runtimes_metropolis_hastings'][:]
runtimes_wolff = f['runtimes_wolff'][:]
f.close()

# Plot runtimes
plt.plot(N_values, runtimes_metropolis_hastings/steps, label='Metropolis-Hastings')
plt.plot(N_values, runtimes_wolff/steps, label='Wolff')
plt.plot(N_values, 1e-6*np.array(N_values)**2, label='$\propto N^2$')
plt.xlabel('System size N')
plt.ylabel('Runtime per iteration/s')
plt.title('Runtime per iteration vs system size')
plt.legend()
plt.yscale('log')
plt.xscale('log')
plt.savefig(os.path.join(os.getcwd(), 'Ising', 'Figures', 'ising_complexity.png'), dpi=300, bbox_inches='tight')
plt.show()
